# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.BigIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('subdivision', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('part', models.CharField(max_length=128)),
                ('measure', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=128)),
                ('order_by', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('is_cashed', models.BooleanField()),
                ('is_taken', models.BooleanField()),
                ('work_phase', models.CharField(default='AD', max_length=2)),
                ('notes', models.CharField(max_length=256)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', related_query_name='work_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='partorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_orders', related_query_name='part_order', to='WAMAStucco.WorkOrder'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', related_query_name='job', to='WAMAStucco.WorkOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('lot', 'subdivision')]),
        ),
    ]
