# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lot',
            field=models.CharField(max_length=15),
        ),
    ]
