# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
