# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0005_auto_20170322_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
