# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0008_auto_20170323_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('NA', 'None'), ('CU', 'CUTTING'), ('MO', 'MOULDING'), ('IN', 'INSTALLING')], default='NA', max_length=2),
        ),
    ]
