# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0010_auto_20170326_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('None', 'NA'), ('Cutting', 'CU'), ('Moulding', 'MO'), ('Installing', 'IN')], default='NA', max_length=2),
        ),
    ]
