# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0016_auto_20170329_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partorder',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
