# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WAMAStucco', '0017_auto_20170402_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', related_query_name='work_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
